spring:
  application:
    name: eureka-ribbon-client-8764
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/
  instance:
    instance-id: b-ribbon-client
    prefer-ip-address: true