server:
  port: 8001

eureka:
  instance:
    hostname: eureka8001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8002.com:8002/eureka/

